import { chmodSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';

type Outcome='pending'|'responded'|'failed'|'interrupted';
type Call={id:string;coauthorId:string;name:string;model:string;gameId:string;startedAt:number;finishedAt?:number;outcome:Outcome;latencyMs?:number;failureCode?:string};
const median=(values:number[])=>{if(!values.length)return null;values.sort((a,b)=>a-b);const mid=values.length>>1;return values.length%2?values[mid]:Math.round((values[mid-1]+values[mid])/2)};

export class CoauthorUsageStore {
  private db:DatabaseSync;
  constructor(file:string){mkdirSync(dirname(file),{recursive:true,mode:0o700});this.db=new DatabaseSync(file);chmodSync(file,0o600);this.db.exec(`PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS coauthor_calls(id TEXT PRIMARY KEY,coauthor_id TEXT NOT NULL,name TEXT NOT NULL,model TEXT NOT NULL,game_id TEXT NOT NULL,started_at INTEGER NOT NULL,finished_at INTEGER,outcome TEXT NOT NULL,failure_code TEXT,latency_ms INTEGER); CREATE INDEX IF NOT EXISTS coauthor_calls_started ON coauthor_calls(started_at); CREATE INDEX IF NOT EXISTS coauthor_calls_identity ON coauthor_calls(coauthor_id,started_at); UPDATE coauthor_calls SET outcome='interrupted',finished_at=started_at,latency_ms=0,failure_code='process_restart' WHERE outcome='pending'; DELETE FROM coauthor_calls WHERE started_at < ${Date.now()-180*86_400_000};`)}
  begin(data:{coauthorId:string;name:string;model:string;gameId:string}){const id=randomUUID(),startedAt=Date.now();this.db.prepare('INSERT INTO coauthor_calls(id,coauthor_id,name,model,game_id,started_at,outcome) VALUES(?,?,?,?,?,?,?)').run(id,data.coauthorId,data.name.slice(0,100),data.model.slice(0,100),data.gameId.slice(0,100),startedAt,'pending');return id}
  finish(id:string,outcome:'responded'|'failed',failureCode?:string){const row=this.db.prepare("SELECT started_at FROM coauthor_calls WHERE id=? AND outcome='pending'").get(id) as {started_at:number}|undefined;if(!row)return;const finishedAt=Date.now();this.db.prepare("UPDATE coauthor_calls SET outcome=?,finished_at=?,latency_ms=?,failure_code=? WHERE id=? AND outcome='pending'").run(outcome,finishedAt,finishedAt-row.started_at,failureCode||null,id)}
  summary(days=30){const since=Date.now()-Math.max(1,Math.min(days,180))*86_400_000;const rows=this.db.prepare('SELECT coauthor_id AS id,name,model,game_id AS gameId,started_at AS startedAt,finished_at AS finishedAt,outcome,latency_ms AS latencyMs,failure_code AS failureCode FROM coauthor_calls WHERE started_at>=? ORDER BY started_at DESC').all(since) as Call[];
    const responded=rows.filter(x=>x.outcome==='responded').length,failed=rows.filter(x=>x.outcome==='failed'||x.outcome==='interrupted').length,latencies=rows.filter(x=>x.outcome==='responded'&&x.latencyMs!=null).map(x=>x.latencyMs!);
    const group=(key:(x:Call)=>string)=>{const map=new Map<string,Call[]>();for(const row of rows){const k=key(row),list=map.get(k)||[];list.push(row);map.set(k,list)}return [...map.entries()].map(([k,list])=>{const ok=list.filter(x=>x.outcome==='responded'),bad=list.filter(x=>x.outcome==='failed'||x.outcome==='interrupted');return {key:k,name:list[0].name,model:list[0].model,calls:list.length,responded:ok.length,failed:bad.length,responseRate:list.length?Math.round(ok.length/list.length*100):0,medianLatencyMs:median(ok.map(x=>x.latencyMs||0)),lastAt:new Date(Math.max(...list.map(x=>x.startedAt))).toISOString()}})};
    const dailyMap=new Map<string,{date:string;calls:number;responded:number;failed:number}>();for(const row of rows){const date=new Date(row.startedAt).toISOString().slice(0,10),item=dailyMap.get(date)||{date,calls:0,responded:0,failed:0};item.calls++;if(row.outcome==='responded')item.responded++;if(row.outcome==='failed'||row.outcome==='interrupted')item.failed++;dailyMap.set(date,item)}
    return {available:true,days,summary:{calls:rows.length,responded,failed,pending:rows.filter(x=>x.outcome==='pending').length,responseRate:rows.length?Math.round(responded/rows.length*100):0,medianLatencyMs:median(latencies),coauthors:new Set(rows.map(x=>x.id)).size},byCoauthor:group(x=>x.id).map(({key,...item})=>({id:key,...item})),byGame:group(x=>x.gameId).map(({key,...item})=>({gameId:key,...item})),daily:[...dailyMap.values()].sort((a,b)=>a.date.localeCompare(b.date))};
  }
}
